Feature/vape 510 faq backend
bcgov/moh-bcer pull request #158
Opened 2022-03-24 05:31 UTC by DRsabadash

includes VAPE-509 front-end ticket work

2022-03-27 21:36 UTC, roy-sagar11 requested changes

2022-03-28 17:07 UTC, roy-sagar11 approved these changes

2022-03-28 22:27 UTC, roy-sagar11 commented on packages/bcer-api/app/src/migrations/1659555307942-FaqTable.ts
> +    name = 'NotesTable1659555306536'
this needs to be updated as well to avoid duplicate name errors during migration!

2022-03-29 17:56 UTC, simensma-fresh approved these changes

2022-03-29 18:00 UTC, merged