Feature/VAPE_390_NOI_RENEWAL : added logic to allow renewal and expiry of Noi
bcgov/moh-bcer pull request #26
Opened 2021-10-18 16:57 UTC by roy-sagar11

- Resolves:

1. NOI will be marked as expired at a given date through env (default 12-01 in MM-DD format);
2.  The expired NOI's will appear on the outstanding NOI table and Businesses will be able to renew the NOI's
3.  A cron job to marked all locations with an expired NOI as closed.
4. Ability to make NOI tables full screen.
5. Ability to select certain NOI's and submit only selected.

- Changes
**Back End**
1. Updated NOI table. added column renewed_at 
2. Added function to calculate NOI status based on renew date and noi expiry date env.
3. Updated createNOi service so that if NOI for the location exists it will update the renewed_at column if not then create a new NOI.
4. Updated location table. added column status and closed_at.
5. Added cron job to run on provided date and mark all location with expired NOI as closed.

**Front End**
1. Added Reusable component FullScreen and TableWrapper that incorporates all new design changes.
2. Added 4 different status for Noi (Submitted, Not Required, Not Submitted and Not Renewed) 
3. businesses are able to renew expired NOI's if the location is still active.
4. Made the submission NOI table row selectable.  

- References - external references (if any)

2021-10-18 21:43 UTC, simensma-fresh requested changes

2021-10-18 21:43 UTC, simensma-fresh commented on packages/bcer-api/app/src/cron/config/cron.config.ts
> +    static getRunCronFlag(): boolean {
I'm wondering if we maybe should change this to toggle based on the name of the cron job? That way we can have a way of disabling individual cron jobs if needed

2021-10-18 21:43 UTC, simensma-fresh commented on packages/bcer-api/app/src/location/entities/location.entity.ts
> +  closed: boolean;
Thoughts on making this a `status` instead? (`CLOSED | ACTIVE | (DELETED)`)

2021-10-18 21:43 UTC, simensma-fresh commented on packages/bcer-api/app/src/location/entities/location.entity.ts
> +  closed: boolean;
Probably covered by VAPE-383, but we should probably add a `closedAt` timestamp to record when the location was closed

2021-10-18 21:43 UTC, simensma-fresh commented on packages/bcer-api/app/src/location/location.service.ts
> +    // TODO: Add location != 'deleted'
Hopefully we won't need this if we end up using the built in `softDelete` TypeORM functionality for deleting a location 🙃  (TypeORM *should* exclude it from queries automatically)

2021-10-19 05:11 UTC, c1495616js commented on packages/bcer-api/app/src/location/entities/location.entity.ts
> +  closed_at: Date;
in js, we use `closedAt` and put the database column name in `@Column({..., name: 'closed_at'})`

2021-10-19 05:17 UTC, c1495616js commented on packages/bcer-retailer-app/app/src/constants/localInterfaces.tsx
>      created_at: Date;
ok, looks like it's because of legacy code. If it's legacy code from the backend, then I think we can just keep it.

2021-10-19 16:02 UTC, jerryfreshworks commented on packages/bcer-api/app/src/location/enums/location-status.enum.ts
> +}
btw, Enum is better to use PascalCase.

![image](https://user-images.githubusercontent.com/46575401/137948620-2405e412-6beb-4a25-89b4-670bebc5b6d0.png)

2021-10-19 16:03 UTC, jerryfreshworks commented on packages/bcer-api/app/src/location/enums/location-status.enum.ts
> +}
`Active`, `Closed`...

2021-10-19 17:10 UTC, ghost approved these changes
💯

2021-10-19 17:32 UTC, simensma-fresh approved these changes
🙌

2021-10-19 17:33 UTC, merged