Feature/VAPE_399: added column to download pdf for existing noi
bcgov/moh-bcer pull request #37
Opened 2021-11-09 20:49 UTC by roy-sagar11

2021-11-12 16:19 UTC, simensma-fresh requested changes

2021-11-12 16:19 UTC, simensma-fresh commented on packages/bcer-retailer-app/app/src/utils/noi.util.tsx
> +  private CalculateTotalCharacters(data: BusinessLocation, legalName: string) {
Can probably make `CalculateTotalCharacters` lower case to make it consistent

2021-11-15 17:22 UTC, simensma-fresh approved these changes

2021-11-15 18:29 UTC, DRsabadash commented on packages/bcer-retailer-app/app/src/components/Noi/NoiTable.tsx
> +  let columns :any = [
do we know the typing of this? if so we should probably create a typedef for it, or at the least in-line type it

2021-11-15 18:30 UTC, DRsabadash commented on packages/bcer-retailer-app/app/src/utils/noi.util.tsx
> +            }}
just a nitpick - we can pass the function to the onClick without needing the wrapping curly-braces, i.e:
`onClick={() => handleDownload(l)}`

2021-11-15 19:34 UTC, DRsabadash approved these changes

2021-11-15 19:56 UTC, merged